const ACTIONS = {
    JOIN: 'join',
    JOINED: 'joined',
    DISCONNECTED: 'disconnected',
    CODE_CHANGE: 'code-change',
    SYNC_CODE: 'sync-code',
    ICODE_CHANGE: 'code-change-input',
    ISYNC_CODE: 'sync-code-input',
    OCODE_CHANGE: 'code-change-output',
    OSYNC_CODE: 'sync-code-output',
    SYNC_LAN: 'sync-lan',
    LAN_CHANGE: 'lan-change',
    LEAVE: 'leave',
    ADD_PEER: 'add-peer',
    REMOVE_PEER: 'remove-peer',
    RELAY_ICE: 'relay-ice',
    RELAY_SDP: 'relay-sdp',
    SESSION_DESCRIPTION: 'session-description',
    ICE_CANDIDATE: 'ice-candidate',
    MUTE: 'mute',
    UNMUTE: 'unmute',
    MUTE_INFO: 'mute-info',
};

module.exports = ACTIONS;
